[phases.setup]
nixPkgs = ["nodejs_22", "yarn-1_x"]

[phases.install]
cmds = ["cp .npmrc.nixpacks \"$HOME/.npmrc\" && yarn install && rm -f \"$HOME/.npmrc\""]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn build:production"]

[start]
cmd = "yarn run preview --host 0.0.0.0 --port ${PORT:-3000}"