[phases.setup]
nixPkgs = ["nodejs_23", "yarn-1_x"]

[phases.install]
cmds = ["cp .npmrc.nixpacks \"$HOME/.npmrc\" && yarn install --frozen-lockfile && rm -f \"$HOME/.npmrc\""]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn --cwd packages/paperlesspaper-web build:production"]

[start]
cmd = "cd packages/paperlesspaper-web && yarn run preview --host 0.0.0.0 --port ${PORT:-3000}"